; Script generated by Presences AI Team
; Inno Setup Script for Presences Spotlight AI Gate Attendance Terminal

#define MyAppName "Presences Spotlight AI"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Team RCA & Presences AI"
#define MyAppURL "https://presences.ai"
#define MyAppExeName "START_SPOTLIGHT.bat"

[Setup]
AppId={{D9A7A1B2-55C1-4D93-9F93-8B39A5B40E80}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\Presences\SpotlightGate
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=README.md
OutputDir=dist
OutputBaseFilename=Presences_Spotlight_Setup_Installer
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "__pycache__\*,dist\*,build\*,*.iss"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"
Name: "{group}\Setup & Config Wizard"; Filename: "{app}\installer_gui.py"; WorkingDir: "{app}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "{app}\SETUP_ON_ANY_PC.bat"; Description: "Run automatic dependency verification"; Flags: postinstall shellexec skipifsilent
Filename: "{app}\installer_gui.py"; Description: "{cm:LaunchProgram,Setup & Configuration Wizard}"; Flags: postinstall shellexec nowait skipifsilent
